import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import fetch from 'node-fetch';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json({ limit: '1mb' }));

const PORT = process.env.PORT || 3001;

app.post('/api/fortune', async (req, res) => {
  try {
    const zodiac = String(req.body?.zodiac || '').trim();
    if (!zodiac) {
      return res.status(400).json({ error: 'zodiac is required' });
    }

    const apiKey = process.env.NOUS_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: 'NOUS_API_KEY is not set in .env' });
    }

    const projectId = process.env.NOUS_PROJECT_ID; // Nouswise requires projectId for routing.

    const response = await fetch('https://inference-api.nousresearch.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: process.env.NOUS_MODEL || 'nousresearch/hermes-4-70b',
        messages: [
          {
            role: 'system',
            content:
              'You are a poetic fortune-teller. Respond with ONLY the fortune text. No preamble, no quotes, no markdown.'
          },
          {
            role: 'user',
            content: `Generate a short fortune for the zodiac sign: ${zodiac}. Keep it vivid but safe. 2-3 sentences maximum.`
          }
        ],
        stream: false,
        ...(projectId ? { extra_body: { projectId } } : {})
      })
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      return res.status(500).json({
        error: 'Nous API request failed',
        status: response.status,
        details: errText
      });
    }

    const data = await response.json();
    const fortune = data?.choices?.[0]?.message?.content;
    if (!fortune) {
      return res.status(500).json({ error: 'No fortune generated by Nous API' });
    }

    return res.json({ fortune });
  } catch (e) {
    return res.status(500).json({ error: e?.message || 'Unknown error' });
  }
});

app.listen(PORT, () => {
  console.log(`Backend listening on http://localhost:${PORT}`);
});

